import PDFDocument from 'pdfkit';
import { prisma } from '@/lib/db';
import { formatMoney } from '@/lib/money';
import { amountsFromJson } from '@/lib/forms1099/forms';

// Renders 1099-NEC / 1099-MISC copies as an informational layout.
// Copy A note: the official red-ink Copy A is e-filed (or printed on IRS
// scannable stock) — this PDF is for records/recipient copies. Recipient TINs
// are truncated on every rendered copy (IRS permits payee-TIN truncation on
// recipient copies; full TINs travel only in the e-file payload).

const BOX_LABELS: Record<string, Record<string, string>> = {
  NEC: { '1': 'Nonemployee compensation' },
  MISC: { '1': 'Rents', '2': 'Royalties', '3': 'Other income' },
};

export async function renderForm1099Pdf(formId: string, copy: 'A' | 'B' | 'C'): Promise<Buffer> {
  const form = await prisma.form1099.findUniqueOrThrow({ where: { id: formId } });
  const payer = form.payer as { name: string; addressLine: string; tinLast4?: string };
  const recipient = form.recipient as { name: string; businessName?: string; addressLine: string; tinLast4?: string; tinType?: string };
  const amounts = amountsFromJson(form.amounts);

  const doc = new PDFDocument({ size: 'LETTER', margin: 40 });
  const chunks: Buffer[] = [];
  doc.on('data', (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));

  const copyNote =
    copy === 'A'
      ? 'Copy A — For IRS (e-filed; this rendering is informational, not scannable red-ink stock)'
      : copy === 'B'
        ? 'Copy B — For Recipient'
        : 'Copy C — For Payer records';

  // Frame
  doc.rect(40, 40, 532, 340).strokeColor('#333333').stroke();
  doc.fontSize(9).fillColor('#666666').text(`Form 1099-${form.formKind} · Tax year ${form.taxYear}`, 48, 48);
  doc.fontSize(16).fillColor('#000000').font('Helvetica-Bold')
    .text(form.formKind === 'NEC' ? 'Nonemployee Compensation' : 'Miscellaneous Information', 48, 62);
  doc.fontSize(9).font('Helvetica').fillColor('#444444').text(copyNote, 48, 84);
  if (form.version > 1) {
    doc.fontSize(11).fillColor('#b91c1c').font('Helvetica-Bold').text('CORRECTED', 470, 48);
    doc.font('Helvetica').fillColor('#000000');
  }

  // Payer block
  doc.moveTo(40, 100).lineTo(572, 100).strokeColor('#cccccc').stroke();
  doc.fontSize(8).fillColor('#888888').text("PAYER'S name and address", 48, 106);
  doc.fontSize(10).fillColor('#000000').text(payer.name, 48, 118);
  doc.fontSize(9).fillColor('#333333').text(payer.addressLine || '—', 48, 132, { width: 250 });
  doc.fontSize(8).fillColor('#888888').text("PAYER'S TIN", 320, 106);
  doc.fontSize(10).fillColor('#000000').text(payer.tinLast4 ? `**-***${payer.tinLast4}` : '—', 320, 118);

  // Recipient block
  doc.moveTo(40, 160).lineTo(572, 160).strokeColor('#cccccc').stroke();
  doc.fontSize(8).fillColor('#888888').text("RECIPIENT'S name and address", 48, 166);
  doc.fontSize(10).fillColor('#000000').text(recipient.businessName || recipient.name, 48, 178);
  if (recipient.businessName) doc.fontSize(9).fillColor('#333333').text(recipient.name, 48, 192);
  doc.fontSize(9).fillColor('#333333').text(recipient.addressLine || '—', 48, recipient.businessName ? 206 : 192, { width: 250 });
  doc.fontSize(8).fillColor('#888888').text("RECIPIENT'S TIN (truncated)", 320, 166);
  doc.fontSize(10).fillColor('#000000').text(
    recipient.tinLast4
      ? recipient.tinType === 'EIN'
        ? `**-***${recipient.tinLast4}`
        : `***-**-${recipient.tinLast4}`
      : '—',
    320,
    178,
  );

  // Amount boxes
  let y = 240;
  doc.moveTo(40, y - 8).lineTo(572, y - 8).strokeColor('#cccccc').stroke();
  const labels = BOX_LABELS[form.formKind] ?? {};
  for (const [box, label] of Object.entries(labels)) {
    const amount = amounts[box] ?? 0n;
    doc.fontSize(9).fillColor('#888888').text(`Box ${box} — ${label}`, 48, y);
    doc.fontSize(12).font('Helvetica-Bold').fillColor('#000000')
      .text(formatMoney(amount, 'USD'), 400, y - 2, { width: 160, align: 'right' });
    doc.font('Helvetica');
    y += 26;
  }

  // Footer
  doc.fontSize(8).fillColor('#888888').text(
    `Status: ${form.status}${form.submissionId ? ` · Submission ${form.submissionId}` : ''} · Version ${form.version}` +
      ` · Generated by Wave 2.0 — verify against current IRS forms/instructions before official use.`,
    48,
    392,
    { width: 520 },
  );

  doc.end();
  return done;
}
